### ISSUE TITLE
''xformers'' and webui line issues

### ISSUE THREAD

**Issue by WorkaholicVR** [acheong08/Diffusion-WebUI#3]
Today i started diffusion webui, there was some errors:
1. xformers issue
![2](https://user-images.githubusercontent.com/116095011/196464802-9b1d1930-b357-4ea0-9473-e8be67f64395.png)
2. webui issue
![66](https://user-images.githubusercontent.com/116095011/196464853-cded7b67-6f52-48cd-9c29-9471a0322d35.png)
After that, there is no local ip address to show, and nothing seems to work

**Comment by acheong08** [comment]
Google Colab seems to provide an outdated version of Python. I will remove xformers until it is updated.

**Comment by acheong08** [comment]
Seems to be an issue with one of the pull requests meant to speed up history. Switching back to stable branch

**Comment by acheong08** [comment]
It has been fixed!
